--- #YAML:1.0
name:               Net-Frame-Layer-Syslog
version:            1.03
abstract:           Syslog layer object
author:
    - Michael Vincent <vin at vinsworld dot com>
license:            artistic
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Net::Frame:           1.09
    Socket::GetAddrInfo:  0.21
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
